name: Terraform Apply

on:
  push:
    paths:
      - 'terraform/**'  # Runs only when Terraform files change
    branches:
      - main

jobs:
  terraform:
    name: Apply Terraform Changes
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Initialize Terraform
      run: |
        cd terraform
        terraform init

    - name: Plan Terraform Changes
      run: |
        cd terraform
        terraform plan

    - name: Apply Terraform Changes
      run: |
        cd terraform
        terraform apply -auto-approve
